# separate test file because it uses a different version of IRremoteESP8266

esphome:
  name: test-fujitsu-264

external_components:
  - source:
      type: local
      path: ../components

esp32:
  board: esp32dev
  framework:
    type: arduino

remote_transmitter:
  id: ir_led
  pin: 4
  carrier_duty_percent: 50%

climate:
  - platform: fujitsu_264
    id: my_fujitsu_264
    name: 'Fujitsu-264'

button:
  - platform: template
    name: 'Toggle powerful'
    on_press:
      then:
        - lambda: |-
            id(my_fujitsu_264).toggle_powerful();

  - platform: template
    name: 'Set fan angle'
    on_press:
      then:
        - lambda: |-
            id(my_fujitsu_264).set_fan_angle(1);

  - platform: template
    name: 'Toggle sterilization'
    on_press:
      then:
        - lambda: |-
            id(my_fujitsu_264).toggle_sterilization();

switch:
  - platform: template
    name: 'Clean'
    optimistic: true
    turn_on_action:
      then:
        - lambda: |-
            id(my_fujitsu_264).set_clean(true);
    turn_off_action:
      then:
        - lambda: |-
            id(my_fujitsu_264).set_clean(false);
